stages:
  - test
  - build

golangci:
  stage: test
  image: golangci/golangci-lint:v1.46-alpine
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "false" || $CI_COMMIT_TAG == null'
  script:
    - golangci-lint run

build:
  stage: build
  image: golang:1.18.2-alpine3.15
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG != null'
  script:
    - |
      for GOOS in linux windows darwin; do
        SUFFIX=$([ $GOOS = "windows" ] && echo ".exe")
        for GOARCH in amd64 386; do
          for BIN in jaroid jaroidfedi; do
            go bild ./cmd/$BIN -o ${BIN}-${CI_COMMIT_TAG}-${GOOS}-${GOARCH}${SUFFIX} &
          done
        done
      done
      wait
  artifacts:
    paths:
      - jaroid-*
      - jaroidfedi-*
