stages:
  - test
  - build

golangci:
  stage: test
  image: golangci/golangci-lint:v1.46-alpine
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "false" || $CI_COMMIT_TAG == null'
  script:
    - golangci-lint run

build:
  stage: build
  image: golang:1.18.2-alpine3.15
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG != null'
  script:
    - |
      for GOOS in linux windows darwin; do
        SUFFIX=$([ $GOOS = "windows" ] && echo ".exe" || true)
        for GOARCH in amd64 386; do
          [ $GOOS = "darwin" ] && [ $GOARCH = "amd64" ] && continue || true;
          for BIN in jaroid jaroidfedi; do
            GOOS=$GOOS GOARCh=$GOARCH go build -o ${BIN}-${CI_COMMIT_TAG}-${GOOS}-${GOARCH}${SUFFIX} ./cmd/$BIN &
          done
        done
      done
      wait
  artifacts:
    paths:
      - jaroid-*
      - jaroidfedi-*
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "jaroid-${CI_COMMIT_TAG}-linux-386"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroid-${CI_COMMIT_TAG}-linux-386"
        - name: "jaroidfedi-${CI_COMMIT_TAG}-linux-386"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroidfedi-${CI_COMMIT_TAG}-linux-386"
        - name: "jaroid-${CI_COMMIT_TAG}-linux-amd64"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroid-${CI_COMMIT_TAG}-linux-amd64"
        - name: "jaroidfedi-${CI_COMMIT_TAG}-linux-amd64"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroidfedi-${CI_COMMIT_TAG}-linux-amd64"

        - name: "jaroid-${CI_COMMIT_TAG}-windows-386.exe"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroid-${CI_COMMIT_TAG}-windows-386.exe"
        - name: "jaroidfedi-${CI_COMMIT_TAG}-windows-386.exe"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroidfedi-${CI_COMMIT_TAG}-windows-386.exe"
        - name: "jaroid-${CI_COMMIT_TAG}-windows-amd64.exe"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroid-${CI_COMMIT_TAG}-windows-amd64.exe"
        - name: "jaroidfedi-${CI_COMMIT_TAG}-windows-amd64.exe"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroidfedi-${CI_COMMIT_TAG}-windows-amd64.exe"

        - name: "jaroid-${CI_COMMIT_TAG}-darwin-amd64"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroid-${CI_COMMIT_TAG}-darwin-amd64"
        - name: "jaroidfedi-${CI_COMMIT_TAG}-darwin-amd64"
          url: "https://gitlab.eientei.org/eientei/jaroid/-/jobs/${CI_JOB_ID}/artifacts/file/jaroidfedi-${CI_COMMIT_TAG}-darwin-amd64"
